CREATE DATABASE LibraryOnlineDb
USE LibraryOnlineDb;

CREATE TABLE BOOKS (
    SUBMISSION_ID INT PRIMARY KEY IDENTITY(1,1),
    DISPLAY_IMAGE VARBINARY(MAX),
	BOOK_NAME VARCHAR (50),
	AUTHOR VARCHAR (50),
    DESCRIPTION  VARCHAR (50),
    SUBMISSION_DATE DATETIME DEFAULT GETDATE(),
    PDF_FILE VARBINARY(MAX) , 
);



